AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 26

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Layout/IndentationConsistency:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false